window.CPO_CSV_DATA = `Ticker,Company,Country,Status,Bucket,Role,Alpha Score,Risk Adj,Hiddenness,Notes,Monopoly Score,Rev Growth Est,Target Upside
CRDO,Credo Technology,US,Public,Core,SerDes / AEC / Optical Interface,9,9,7,SerDes/DSP leader. 200%+ realization cycle. [ Val: \$22.06B | P/E: 65.7x | Rev: +201.5% @ \$119.59 ],FY26: 200%+ realization,201% (FY26 AEC/SerDes),3x
BESIY,Besi (BE Semi),US,Public,Core,Hybrid Bonding Equipment,10,9,9,Hybrid bonding leader. Multi-year backlog for logic-optics fusion. [ Val: \$19.60B | P/E: 128.3x | Rev: +8.4% @ \$248.90 ],250% (HB Tool demand),250% (HB Tool demand),3x
KLIC,Kulicke & Soffa,US,Public,Hidden,Thermocompression Bonders,10,8,9,Essential US-listed supplier for thermocompression bonding near optical I/O. [ Val: \$4.05B | P/E: N/A | Rev: +20.2% @ \$77.46 ],35% (TC Bonders),40% (Bonder recovery),1x-2x
ENTG,Entegris,US,Public,Hidden,CMP Slurries / Chemicals,10,9,8,Atomic-level polishing chemicals. Mandatory for hybrid bonding surfaces. [ Val: \$20.60B | P/E: 86.7x | Rev: -3.0% @ \$135.32 ],40% (CMP Slurries),25% (CMP/Chemicals),1x-2x
ONTO,Onto Innovation,US,Public,Hidden,Adv Packaging Inspection,10,8,7,FY26: >25% (HBM/Packaging >30%) [ Val: \$12.78B | P/E: 92.5x | Rev: +1.1% @ \$257.14 ],40% (Duopoly vs KLAC),30% (Metrology/Inspection),1x-2x
DNPCY,Dai Nippon Printing,US,Public,Hidden,Glass Core Substrates,10,8,10,Transforming display IP into Glass Substrates (GCS). Next generation CPO base.,30% (Glass Core R&D),20% (GCS pilot),1x-2x
COHR,Coherent,US,Public,Core,Lasers & InP Substrates,10,8,4,FY26: 19.4% / FY27: 23.2% [ Val: \$57.65B | P/E: 304.5x | Rev: +17.5% @ \$307.50 ],50% (CW Laser Duopoly),23.2% (FY27 Photonics),3x
ALRIB.PA,Riber,Europe,Public,Alpha,MBE Epitaxy Equipment,10,3,10,Tied to new datacom contracts [ Val: \$0.19B | P/E: 60.0x | Rev: -22.1% @ \$9.00 ],100% (Industrial MBE),300% (MBE 6k industrial ramp),5x
SMHN.DE,SUSS MicroTec,Europe,Public,Hidden,Hybrid Bonding Equipment,10,8,8,Explosive growth in nano-imprint lithography for micro-optics. Pure-play on 2.5D/3D packaging. Overlooked by US retail. [ Val: \$1.17B | P/E: 20.7x | Rev: -21.5% @ \$60.95 ],Consistent double-digit growth,Leader in wafer-to-wafer bonding for CPO integration.,3x
AMAT,Applied Materials,US,Public,Core,Packaging Equipment,10,9,3,30% (Overall WFE) [ Val: \$317.04B | P/E: 41.0x | Rev: -2.1% @ \$399.49 ],Driven by AI packaging,Providing the tools for glass substrate and SiPh fabrication.,1x-2x
ALAB,Astera Labs,US,Public,Moonshot,PCIe / CXL Retimers,10,7,4,50% (Retimer leader) [ Val: \$25.37B | P/E: 122.2x | Rev: +91.8% @ \$149.05 ],250% (Aries/Leo PCIe Ramp),The copper-side equivalent of the CPO bottleneck.,3x
SNPS,Synopsys,US,Public,Core,EDA Tools for SiPh,10,9,3,70% (EDA Monopoly) [ Val: \$75.14B | P/E: 60.3x | Rev: +65.5% @ \$392.24 ],Steady 15%,Essential software for designing photonic circuits.,1x-2x
ANSS,Ansys,US,Public,Core,Simulation (Lumerical),10,9,4,60% (Photonics Sim),Steady,Standard for simulating light behavior in chiplets.,1x-2x
LITE,Lumentum,US,Public,Core,Lasers / optics,10,8,4,50% (UHP CW Diodes) [ Val: \$64.07B | P/E: 263.1x | Rev: +65.5% @ \$897.30 ],400% (CPO Laser segment ramp),400% (CPO Laser segment),3x
LWLG,Lightwave Logic,US,Public,Moonshot,Polymer EO Modulators,10,4,10,80% (Polymer Modulator) [ Val: \$1.58B | P/E: N/A | Rev: +594.5% @ \$10.60 ],500%+ Potential (Phase II Vol),500% (Modulator volume),10x
2455.TW,Visual Photonics,Taiwan,Public,Moonshot,InP / GaAs Foundry,10,7,9,50% (Epi Foundry) [ Val: \$54.98B | P/E: 101.0x | Rev: +32.8% @ \$299.00 ],300% (Foundry capacity tight),300% (Epi Foundry),5x
POET,POET Tech,US,Public,Moonshot,Optical engine / integration,10,9,8,Direct SiPh engine architect. Breakthrough platform for 1.6T/3.2T. [ Val: \$1.08B | P/E: N/A | Rev: +1075.3% @ \$7.04 ],1500% Potential (Pilot to \$100M+),1500% (Pilot ramp),10x
CelestialAI,Marvell/CelestialAI,US,Private,Private,Optical Compute Fabric,10,6,4,🔒 Acquired by MRVL (Marvell) — Optical compute fabric. 300% (Segment internal),Acquired tech integration into Teralynx/Marvell.,TBD,1x-2x
AYAR,Ayar Labs,US,Private,Private,TeraPHY Optical I/O,10,8,9,"🔒 Private — \$3.75B valuation, backed by NVDA/AMD/MediaTek. 500% (Pre-revenue ramp)",Private but tracking via Intel/Nvidia partnerships.,TBD,10x
RANV,Ranovus,US,Private,Private,Odin Photonic Engine,10,6,9,"🔒 Private — Ranovus Odin CPO engine, direct-drive architecture. 300% (Hyperscale ramp)",Direct interface with 51.2T switches.,TBD,10x
AXTI,AXT Inc,US,Public,Moonshot,InP Substrates,9,6,8,InP/GaAs materials alpha. 5x YTD runner. [ Val: \$3.57B | P/E: N/A | Rev: -8.2% @ \$64.18 ],200-300% (InP Substrate Gap),200% (InP substrate shortage),5x
ASMPT,ASMPT,US,Public,Hidden,Die bonders / assembly equipment,9,8,9,AMICRA division: near-monopoly on sub-0.3um die bonders. Every OSAT/foundry doing CPO must buy AMICRA machines. P/E mid-teens. [ Val: \$47.71B | P/E: 43.9x | Rev: N/A @ \$114.20 ],Near-monopoly (sub-0.3um bonders),20% (AMICRA CPO bonders),3x
NDSN,Nordson,US,Public,Hidden,Precision Dispensing / Plasma,9,9,9,ASYMTEK division dominates precision dispensing for CPO/CoWoS underfill. Driven by parallel CoWoS expansion. [ Val: \$15.36B | P/E: 29.8x | Rev: +8.8% @ \$275.28 ],70% (ASYMTEK Underfill),10% (ASYMTEK underfill),1x-2x
TWCPY,Towa Corp,US,Public,Hidden,Compression Molding,9,8,9,Near-monopoly in precision molding for TSMC CoWoS / Optical packaging lines. [ Val: \$205.42B | P/E: 33.4x | Rev: +13.7% @ \$2738.00 ],70% (Compression Molding),15% (CoWoS molding),1x-2x
AIXNY,Aixtron,US,Public,Hidden,MOCVD / epitaxy tools,9,8,8,Other MOCVD duopoly leader. Optoelectronics is #1 growth driver for 2026. InP laser demand mandatory. [ Val: \$4.31B | P/E: 50.2x | Rev: -17.5% @ \$38.17 ],50% (MOCVD Duopoly w/VECO),15% (Optoelectronics #1 driver),1x-2x
MKSI,MKS Instruments,US,Public,Hidden,Laser Via Drilling,9,8,8,ESI/Atotech acquisitions give monopoly on laser drilling micro-vias in GCS and ABF substrates. [ Val: \$18.09B | P/E: 61.4x | Rev: +10.6% @ \$268.77 ],40% (Laser Via Drilling),12% (ESI/Atotech integration),1x-2x
VECO,Veeco,US,Public,Hidden,MOCVD / epitaxy tools,10,8,8,MOCVD leader for InP light sources. Hidden laser arms dealer. [ Val: \$2.42B | P/E: 67.9x | Rev: -9.4% @ \$40.04 ],50% (MOCVD Duopoly w/AIXA),20% (InP MOCVD backlog),3x
ASMIY,ASM International,US,Public,Hidden,Atomic Layer Deposition,9,9,6,FY26: 14% (ALD CAGR 9-13%) [ Val: \$43.64B | P/E: 51.8x | Rev: -13.7% @ \$886.66 ],55% (Single-Wafer ALD),14% (ALD CAGR 9-13%),1x-2x
CAMT,Camtek,US,Public,Hidden,Optical Metrology,9,8,7,Dominant 2D/3D Optical Metrology for advanced packaging bumps. Direct CPO quality control. [ Val: \$8.12B | P/E: 166.2x | Rev: +9.2% @ \$174.53 ],50% (2D/3D Metrology),20% (Adv packaging inspection),1x-2x
NVMI,Nova,US,Public,Hidden,Optical Metrology,9,8,7,World-class metrology capturing CPO inspection cycles. X-ray and OCD platforms. [ Val: \$15.77B | P/E: 62.5x | Rev: +14.3% @ \$496.06 ],40% (OCD Metrology),18% (Metrology expansion),1x-2x
IBIEY,Ibiden,US,Public,Hidden,ABF & Core Substrates,9,7,8,Dominant high-end IC substrate supplier alongside Shinko. ABF pricing pressure from Palliser activism. [ Val: \$2761.18B | P/E: 83.3x | Rev: N/A @ \$9888.00 ],35% (High-end Substrates),12% (ABF substrate demand),1x-2x
TSEM,Tower Semi,US,Public,Core,Foundry / photonics manufacturing,9,9,6,The 'TSMC of Photonics'. Major foundry leverage. [ Val: \$24.22B | P/E: 105.5x | Rev: +13.7% @ \$203.59 ],40% (SiPh Foundry),25% (SiPh foundry ramp),3x
LPKF,LPKF,US,Public,Hidden,Glass via drilling / TGV tools,9,7,9,Only commercially viable Through-Glass Via (TGV) drilling. Patented LIDE process. Glass substrate supercycle = 5-10x potential.,100% (LIDE TGV Patent),50% (LIDE commercialization),5x
SHWDY,Resonac,US,Public,Hidden,Epoxy / Mold Compounds,9,8,8,Massive supplier of critical underfill and EMC for advanced packaging thermal management. [ Val: \$12.80B | P/E: 70.0x | Rev: -0.8% @ \$70.75 ],60% (EMC/Underfill),10% (Underfill materials),1x-2x
INNO,InnoLight,US,Public,Core,Optical modules,9,7,8,"Major Chinese transceiver beneficiary. 800G ramping, 1.6T next. Scale advantage.",30% (China Transceivers),40% (800G/1.6T modules),1x-2x
300502.SZ,Eoptolink,China,Public,Private,Optical modules,9,7,8,TFLN modulator pioneer for 1.6T. Data center optical module leader in China. [ Val: \$519.37B | P/E: 68.9x | Rev: +152.5% @ \$522.50 ] [Mainland China - Untradeable via standard US brokerage],20% (DC Modules),35% (Data center modules),1x-2x
SMTOY,Sumitomo Electric,US,Public,Hidden,InP Substrates,9,8,8,70% InP Supply Gap expected 2025-2026. Japanese quality premium. [ Val: \$53.98B | P/E: 39.1x | Rev: N/A @ \$68.10 ],60% (InP Substrates),15% (InP supply gap),3x
ATS.VI,AT&S,Europe,Public,Hidden,Advanced IC Substrates,9,7,8,30% (High-end logic) [ Val: \$2.59B | P/E: 20.2x | Rev: +17.9% @ \$66.60 ],Recovery play 2026,Scaling glass core substrate R&D for AI/HPC.,1x-2x
PLET.DE,Plan Optik,Europe,Public,Moonshot,Micro-structured Glass,9,6,9,85% (Niche),300% (TGV Glass packaging),Crucial for vias and precision glass components in CPO.,5x
7741.T,Hoya Corp,Japan,Public,Core,Glass Substrates/Blanks,9,9,7,40% (High-end Mask Blanks) [ Val: \$9931.82B | P/E: 48.5x | Rev: +10.5% @ \$29490.00 ],Consistent,Crucial for the extreme precision required in SiPh lithography.,1x-2x
FRA:MRK,Merck KGaA,US,Public,Core,Specialized Chemicals,9,9,5,Oligopoly in CMP chemicals [ Val: \$300.20B | P/E: 16.7x | Rev: +5.0% @ \$121.42 ],Steady,Crucial for Atomic Layer Deposition and CMP polishing in SiPh.,1x-2x
SMTC,Semtech,US,Public,Core,Linear Drive / TIA,9,7,6,30% [ Val: \$7.92B | P/E: N/A | Rev: +9.3% @ \$85.22 ],Driven by LPO/CPO,Crucial analog front-end components for optical engines.,1x-2x
KEYS,Keysight,US,Public,Core,Test & Measurement,9,9,4,40% [ Val: \$55.60B | P/E: 57.2x | Rev: +23.3% @ \$324.18 ],Steady,Providing the testing rigs for 1.6T transceivers.,1x-2x
TER,Teradyne,US,Public,Core,Automated Test,9,8,5,40% [ Val: \$57.61B | P/E: 106.4x | Rev: +43.9% @ \$367.99 ],Steady,Testing the final co-packaged modules at scale.,1x-2x
CSCO,Cisco,US,Public,Core,Networking,9,9,5,Acacia SiPh leader [ Val: \$324.86B | P/E: 29.6x | Rev: +9.7% @ \$82.22 ],Steady,Pioneer in co-packaging transceivers into large switches.,1x-2x
AAOI,Applied Opto,US,Public,Moonshot,Optical modules / transceivers,9,5,6,Direct transceiver play. 5x YTD but still undervalued vs cycle. [ Val: \$11.70B | P/E: N/A | Rev: +33.9% @ \$150.60 ],300% (1.6T Hyperscale pivot),119% (1.6T AI pivot),5x
SCINTIL,Scintil Photonics,US,Private,Private,III-V on Si Integration,9,5,9,"🔒 Private — III-V on Silicon, pre-revenue R&D stage. 400% (Scaling SoC)",Foundry partner for monolithic integration.,TBD,10x
NOVT,Novanta,US,Public,Hidden,Precision Motion / Alignment,8,8,9,Celera Motion sub-nanometer stages for active optical alignment in CPO assembly. [ Val: \$4.47B | P/E: 85.2x | Rev: +8.5% @ \$125.23 ],Niche (sub-nm alignment),10% (Precision motion),1x-2x
MTRN,Materion,US,Public,Hidden,Thin-Film Optical Materials,8,8,9,Sputtering targets and optical coating materials for SiPh chips. 70%+ periodic table coverage. [ Val: \$3.40B | P/E: 45.6x | Rev: +12.1% @ \$163.34 ],70% (Periodic table coverage),8% (Thin-film materials),1x-2x
COHU,Cohu,US,Public,Hidden,Thermal Test Handlers,8,7,8,Thermal testing handlers for stress-testing burning hot optics and CPO modules. [ Val: \$1.76B | P/E: N/A | Rev: +29.9% @ \$37.34 ],30% (Test Handlers),10% (Thermal handlers),1x-2x
ASE,ASE Tech,US,Public,Core,OSAT / packaging,8,9,7,Key packaging/assembly node. Breaking ground on 6 plants.,40% (Global OSAT),20% (6 new plants),1x-2x
APH,Amphenol,US,Public,Hidden,AI Interconnects / Fiber Optic,8,9,5,33% AI data center interconnect share. CommScope CCS deal. \$7B quarterly revenue. The roads of CPO. [ Val: \$173.04B | P/E: 42.1x | Rev: +49.1% @ \$140.75 ],33% (AI DC Interconnect),15% (AI interconnects),1x-2x
MYCRF,Mycronic (MRSI),US,Public,Hidden,Photonic Die Bonders,8,9,9,Direct competitor to ASMPT in sub-micron optical placement accuracy. [ Val: \$46.47B | P/E: 29.8x | Rev: -1.8% @ \$238.00 ],Competitor to AMICRA,15% (MRSI bonders),1x-2x
PROB.MI,Technoprobe,Europe,Public,Hidden,Advanced Probe Cards,8,8,8,Ultra-high-density IC testing before packaging; rapidly stealing market share.,Rapidly gaining share,20% (Probe cards),1x-2x
6941.T,Yamaichi,Japan,Public,Hidden,Test sockets / connectors,8,7,9,Ultra-high-speed test sockets for 800G/1.6T. Highly profitable. Steep discount to US equivalents. [ Val: \$168.52B | P/E: 29.5x | Rev: +50.2% @ \$9160.00 ],50% (High-speed Optical Sockets),20% (Test socket demand),1x-2x
SOI,Soitec,US,Public,Core,Substrates / engineered wafers,9,8,7,Advanced substrates bottleneck. French SiPh champion.,80% (FD-SOI Substrates),15% (Substrate recovery),3x
CLS,Celestica,US,Public,Hidden,Contract Manufacturing,8,8,7,Quietly building the 400G/800G/1.6T networking switches for hyperscalers. [ Val: \$40.42B | P/E: 49.0x | Rev: +43.6% @ \$351.31 ],Contract Mfg leader,20% (Networking switches),1x-2x
GLW,Corning,US,Public,Core,Fiber / cable / connectivity,8,9,5,AI data-center connectivity and glass/fiber infrastructure. [ Val: \$147.10B | P/E: 93.6x | Rev: +20.4% @ \$171.24 ],35% (Optical Fiber),10% (Fiber/connectivity),1x-2x
MRVL,Marvell,US,Public,Core,Networking silicon / DSP,8,9,4,System-level optical/networking exposure. [ Val: \$112.36B | P/E: 41.9x | Rev: +22.1% @ \$128.49 ],Hyper-growth in AI DSP,25% (AI DSP/networking),1x-2x
AVGO,Broadcom,US,Public,Core,Networking silicon / custom silicon,8,9,4,AI infrastructure beneficiary. [ Val: \$1761.62B | P/E: 72.4x | Rev: +29.5% @ \$371.55 ],Dominating CPO Switch,15% (Networking silicon),1x-2x
PTF,Invesco Tech Momentum ETF,US,ETF,ETF,Momentum Tech ETF,8,8,8,Rules-based dragnet that catches small-cap CPO equipment names at breakout.,TBD,TBD,1x-2x
GFS,GlobalFoundries,US,Public,Core,SiPh Foundry PDKs,8,9,6,SiPh segment hitting \$1B by 2028 [ Val: \$26.87B | P/E: 30.8x | Rev: N/A @ \$48.93 ],40% (SiPh Foundry),10% (SiPh foundry),1x-2x
5201.T,AGC Inc,Japan,Public,Core,Specialty Glass,8,9,6,30% (Materials) [ Val: \$1237.45B | P/E: 17.9x | Rev: +2.5% @ \$5827.00 ],Steady,Providing base glass chemistry for 3D packaging.,1x-2x
SCHN.PA,Schneider Electric,Europe,Public,Core,Data Center Infrastructure,8,9,4,Oligopoly,Steady,"""Energy bottleneck play; CPO reduces power consumption",1x-2x
PSTG,Pure Storage,US,Public,Core,All-Flash Data,8,8,5,Storage Alpha [ Val: \$20.14B | P/E: 110.8x | Rev: N/A @ \$60.94 ],Steady,AI clusters need fast storage tied to the broad photonics fabric.,1x-2x
STM,STMicroelectronics,US,Public,Core,SiPh Manufacturing,8,8,6,15% [ Val: \$35.09B | P/E: 219.3x | Rev: +0.2% @ \$39.48 ],Steady,Mass production partner for Cisco/Acacia.,1x-2x
6361.T,Ebara,Japan,Public,Core,CMP Polishing,8,8,7,30% (Global CMP) [ Val: \$2339.56B | P/E: 30.9x | Rev: +51.2% @ \$5124.00 ],Rising with AI,Polishing the ultra-flat surfaces required for hybrid bonding.,1x-2x
TEL,TE Connectivity,US,Public,Core,Interconnects,8,9,5,Global leader [ Val: \$67.45B | P/E: 33.1x | Rev: +21.7% @ \$229.78 ],Steady,Providing the physical plugs for optical fibers.,1x-2x
KLAC,KLA,US,Public,Core,Inspection / metrology,7,9,4,Process control beneficiary. [ Val: \$228.27B | P/E: 50.5x | Rev: +7.2% @ \$1737.28 ],50% (Wafer Inspection),8% (Process control),1x-2x
MTSI,MACOM,US,Public,Core,Mixed-signal / photonics enablement,7,8,5,Enabler across optical networking. [ Val: \$19.36B | P/E: 116.3x | Rev: +24.5% @ \$258.11 ],30% (Mixed-signal Photonics),15% (Optical networking),1x-2x
FN,Fabrinet,US,Public,Core,Optical assembly / manufacturing,7,8,5,Critical contract manufacturing in optics. [ Val: \$23.72B | P/E: 63.3x | Rev: +35.9% @ \$662.13 ],Critical OEM partner,12% (Optical assembly),1x-2x
AMKR,Amkor,US,Public,Core,Advanced packaging / OSAT,7,8,5,Packaging leverage if CPO ramps. [ Val: \$14.36B | P/E: 38.6x | Rev: +15.9% @ \$57.96 ],20% (OSAT),10% (Adv packaging ramp),1x-2x
AEHR,Aehr,US,Public,Alpha,Burn-in / test,9,5,8,Wafer-level burn-in for AI photonics. 5x potential on mass CPO. [ Val: \$2.22B | P/E: N/A | Rev: -43.7% @ \$70.43 ],60% (Wafer-level burn-in),40% (SiPh burn-in pivot),3x
TYO:6028,TechnoPro,Japan,Public,Hidden,Specialized Engineering,7,8,9,20%,Steady,Supplying the scarce engineering talent for SiPh integration lines.,1x-2x
VIAV,Viavi Solutions,US,Public,Hidden,Optical Test,7,7,8,30% [ Val: \$9.67B | P/E: N/A | Rev: +36.4% @ \$41.79 ],Cyclical,Critical for field-testing fiber deployments in AI clusters.,1x-2x
5801.T,Furukawa Electric (FITEL),Japan,Public,Hidden,Remote Laser Sources,9,7,10,FITEL brand: highest-power C/O-band CW lasers. NVDA/AVGO/Ayar CPO roadmaps depend on blind-mate ELSFP. Conglomerate discount. [ Val: \$3221.95B | P/E: 91.7x | Rev: +8.5% @ \$45800.00 ],70% (High-Power CW),Photonics segment surging,3x
3105.TW,Win Semiconductors,Taiwan,Public,Alpha,III-V Foundry (InP/GaAs),10,7,9,Foundational to photonics + humanoids + space. AVGO lead customer. Private placement = likely T1 semi (NVDA) taking stake. [ Val: \$196.71B | P/E: 116.3x | Rev: +29.4% @ \$464.00 ],60% (III-V Foundry),100%+ (Capacity ramp),5x
ASX,ASE Technology (ADR),US,Public,Core,OSAT / CPO Mass Production,9,9,5,CEO confirmed CPO mass production H2 2026. 6 new plants. Largest expansion year ever. The packaging bottleneck. [ Val: \$54.41B | P/E: 45.2x | Rev: +9.6% @ \$24.84 ],40% (Global OSAT),25% (CPO packaging boom),1x-2x
FORM,FormFactor,US,Public,Hidden,Optical Wafer Probe Cards,8,7,8,Specialized optical probe cards for testing SiPh wafers before dicing. 100% mandatory test step. [ Val: \$9.65B | P/E: 179.4x | Rev: +13.6% @ \$123.80 ],50% (Optical Probes),20% (SiPh test ramp),1x-2x
6451.TW,ShunSin Technology,Taiwan,Public,Hidden,SiPh Packaging (Foxconn),8,7,9,"Foxconn subsidiary for advanced SiPh packaging. If Foxconn builds NVDA racks, ShunSin handles optical packaging. [ Val: \$45.87B | P/E: 1661.5x | Rev: +22.2% @ \$432.00 ]",Foxconn captive,50%+ (CPO ramp),3x
HPS-A.TO,Hammond Power Solutions,Canada,Public,Hidden,Power transformers for AI DCs,7,7,9,Critical power infrastructure for AI data centers. Transformer supply bottleneck. [ Val: \$2.57B | P/E: 35.6x | Rev: +21.9% @ \$215.66 ],Niche leader,30%+ (DC buildout),1x-2x
3363.TW,FOCI Fiber Optic,Taiwan,Public,Hidden,Fiber Array Units (FAU),8,6,9,Physical connectors linking fibers to SiPh chips. Tied to Himax WLO. Critical CPO assembly component. [ Val: \$89.09B | P/E: 4900.0x | Rev: +8.6% @ \$784.00 ],30% (FAU),40%+ (CPO assembly),3x
4979.TW,LuxNet Corp,Taiwan,Public,Hidden,Active Laser Components,8,6,9,Active laser diodes for CPO transceivers. TWSE momentum play in the Taiwan photonics ecosystem. [ Val: \$63.31B | P/E: 84.8x | Rev: +10.1% @ \$449.50 ],Taiwan niche,50%+ (Laser demand),3x
ENVX,Enovix,US,Public,Hidden,Advanced battery / energy density,7,5,8,Serenity ETF pick. Silicon anode batteries. AI DC power density angle. [ Val: \$1.32B | P/E: N/A | Rev: +15.9% @ \$6.09 ],Emerging,Scaling (Fab 2 ramp),3x
CIEN,Ciena,US,Public,Core,DCI Coherent Optics,8,8,5,WaveLogic coherent optics global standard for long-haul Data Center Interconnect (DCI). [ Val: \$70.17B | P/E: 312.0x | Rev: +33.1% @ \$496.02 ],40% (DCI Coherent),15% (DCI growth),1x-2x
NOK,Nokia (Optical Networks),US,Public,Core,Optical Transport/Routing,7,8,5,High-capacity optical transport and carrier-grade routing. Backbone of global AI internet. [ Val: \$52.81B | P/E: 72.8x | Rev: +2.4% @ \$9.46 ],30% (Optical Transport),8% (NOC segment),1x-2x
ALMU,Alumea,US,Private,Moonshot,SiPh Engines (1.6T/3.2T),8,5,9,High-efficiency SiPh engines for 1.6T/3.2T speeds where traditional optics fail. @FinnStockinger Layer 5 pick. [ Val: \$0.19B | P/E: N/A | Rev: -21.1% @ \$10.76 ],Emerging,Pre-revenue (SiPh ramp),5x
ASML,ASML Holdings,US,Public,Core,EUV Lithography,9,10,2,Absolute monopoly on EUV. Every advanced SiPh and CPO chip requires ASML tools. [ Val: \$580.46B | P/E: 51.3x | Rev: +4.9% @ \$1478.28 ],100% (EUV Monopoly),15% (AI/HPC demand),1x-2x
ICHR,Ichor Holdings,US,Public,Hidden,Gas/Chemical Delivery Systems,7,7,8,Critical fluid delivery systems for MOCVD and CVD processes in InP laser fabrication. [ Val: \$2.00B | P/E: N/A | Rev: -4.2% @ \$57.50 ],30% (Gas Panels),12% (Semi equipment),1x-2x
ETN,Eaton Corp,US,Public,Core,Data Center Power,8,9,5,Critical power management for AI data centers. Electrical infrastructure bottleneck. [ Val: \$156.53B | P/E: 38.6x | Rev: +13.1% @ \$403.00 ],25% (Power Mgmt),12% (DC buildout),1x-2x
INRI,Inari Amertron,US,Public,Hidden,Advanced Packaging OSAT,8,7,9,Malaysian OSAT capturing CPO packaging overflow from Taiwan. Photonics testing capability. [ Val: \$5.44B | P/E: 28.6x | Rev: -12.1% @ \$1.43 ],30% (MY Packaging),20% (OSAT ramp),1x-2x
ANET,Arista Networks,US,Public,Core,AI Networking Switches,9,9,4,Hyperscale networking switches. Direct CPO integration path for 800G/1.6T. [ Val: \$185.56B | P/E: 53.4x | Rev: +28.9% @ \$147.35 ],35% (DC Switching),25% (AI networking),1x-2x
5713.T,Sumitomo Metal Mining,Japan,Public,Hidden,High-Purity Indium Monopoly,9,8,10,The 800lb gorilla of Indium supply. MONOPOLY. [ Val: \$2701.74B | P/E: 112.4x | Rev: N/A @ \$9986.00 ],90% (High-Purity Indium),12% (Indium CAGR),2x
UMI.BR,Umicore,Europe,Public,Hidden,Indium Recycling / Dross,8,8,9,Key recycling plant for Indium Dross from laser fabs. [ Val: \$4.22B | P/E: 11.0x | Rev: +44.1% @ \$17.55 ],40% (Indium Recycling),8% (Circular Semi Materials),1x-2x
NEO.TO,Neo Performance Materials,Canada,Public,Alpha,Specialty Metal Precursors,9,5,8,Indium/Gallium precursor chemistry. High volatility pure-play. [ Val: \$0.92B | P/E: N/A | Rev: -10.8% @ \$22.15 ],35% (Precursors),25% (Semi chemicals),3x
0097.KL,ViTrox,Malaysia,Public,Alpha,Automated Optical Inspection (AOI),9,7,8,Dominant in semi-backend inspection. Shifting heavily to photonics/CPO inspection. [ Val: \$8.58B | P/E: 64.7x | Rev: +57.2% @ \$4.53 ],30% (AOI),20% (CPO testing),2x
6408.TW,Browave,Taiwan,Public,Hidden,Laser/Optical Sub-Assemblies,8,6,9,Key OEM for optical sub-assemblies. Massive transceiver beneficiary.,25% (Optics),15% (CPO packaging),2x-3x
,ASMPT Ltd,Hong Kong,,Core,Sub-micron Die Bonding (AMICRA),10,4,9,Monopoly on CPO die bonders. Essential for ASE/TSMC CPO plants.,,,5x
,Ajinomoto,Japan,,Core,ABF Film Chokepoint,10,3,8,"Global monopoly on ABF (Ajinomoto Build-up Film). Every AI chip substrate — CoWoS, FOPLP, glass core — requires ABF. Was incorrectly labeled AI Hub (demand anchor). Fixed to Core: this is a physical chokepoint, not a consumer/demand player.",,,3x
,Süss MicroTec,Europe,,Core,Nano-Lithography / Micro-Optics,9,6,9,Critical bottleneck for lens arrays in CPO modules.,,,4x
,Yamaichi Electronics,Japan,,Alpha,High-Speed CPO Test Sockets,9,5,9,Testing bottleneck for 800G/1.6T transceivers.,,,5x
,LPKF Laser,Europe,,Moonshot,Glass Core Substrates (TGV),10,8,10,LIDE tech is the holy grail for through-glass vias in CPO packaging.,,,10x
,IPG Photonics,US,,Core,High-Power Fiber Laser / Pump Laser,7,7,5,World leader in high-power fiber lasers. Pump laser tech relevant to Erbium-doped fiber amplifiers (EDFAs) used in long-reach CPO optical links. Less direct than LITE/COHR (no CW ELS for CPO) but relevant for datacenter interconnect amplification. Revenue headwinds from industrial slowdown. Monitor for CPO pivot.,,8%,1.5x
,Clearfield Inc,US,,Hidden,Fiber Management / Outside Plant CPO Connectivity,6,6,7,Fiber management systems and fiber distribution hubs. End-to-end fiber connectivity as hyperscalers build out the physical fiber fabric feeding CPO switches. More adjacent than direct CPO play — benefits from fiber build-out. Small-cap with hyperscaler exposure. Added from research queue 2026-04-10.,,15%,1.5x
,nLIGHT Inc,US,,Hidden,High-Power Semiconductor Laser / Potential ELS Pivot,6,7,7,High-power semiconductor laser manufacturer. Currently focused on defense (fiber lasers for directed energy) and industrial. Core laser physics expertise is directly applicable to ELS (External Laser Sources) for CPO. Watch for any CPO pivot announcement or hyperscaler customer win. Catalyst: US Govt defense contracts provide stable revenue while optionality builds. Added from research queue 2026-04-10.,,18%,2x
SIVE,Sivers Semiconductors AB,Sweden,Public,Alpha,Laser / photonics components,10,7,9,Sivers Semiconductors AB - PRIMARY LISTING: Nasdaq Stockholm (SIVE.ST). US OTC: SIVEF. Last independent InP foundry (Glasgow). Light source for JDSU/MRVL. CHIPS Act \$11.6M recipient. Trades at 1/4 LWLG valuation. OTC volume is limited - use SIVE.ST for meaningful price discovery.,Independent InP Fab,100%+ (InP foundry ramp),5x
IQE.L,IQE plc,UK,Public,Alpha,InP Epitaxy,9,7,7,"IQE plc - PRIMARY LISTING: London Stock Exchange (IQE.L). US OTC: IQEPF (limited liquidity). 40% global epiwafer market share. Point72 aggressively buying. Critical InP/GaAs epiwafer supplier, demand visibility into 2026. 40% (Global Epi) [ Valuation: \$0.36B @ \$37.00 ]",Volatile but high leverage,Essential foundry for InP optical wafers.,1x-2x
6146.T,Disco Corp,Japan,Public,Core,Dicing/Grinding,10,9,6,80% (Slicing Monopoly) [ Val: \$7252.92B | P/E: 57.5x | Rev: +16.8% @ \$66890.00 ] US ADR: DSCSY.,Hyper-growth,Slicing the InP and Silicon wafers at nano-scale without defects.,1x-2x
6890.T,Ferrotec,Japan,Public,Hidden,Micro-TECs / thermal control,9,8,9,Undisputed king of Micro-TECs. Every optical transceiver needs one to cool the laser. <10x P/E. Textbook buy-and-hold. [ Val: \$326.93B | P/E: 29.2x | Rev: +5.1% @ \$6980.00 ] US OTC: FERRF.,80% (Micro-TEC Monopoly),15% (TEC demand surge),3x
SOI.PA,Soitec,France,Public,Core,Photonics-SOI Wafer Monopoly,10,6,8,95%+ global share in SiPho wafers. CPO transition demands 4x the wafer content vs pluggables.,,,
AEHR,Aehr Test Systems,US,Public,Alpha,Wafer-Level SiPho Burn-In,10,4,7,Stage 2 testing. Forces every wafer through infant mortality zone before shipping. Necessary tollbooth for compounding laser failure rates.,,,
VIAV,Viavi Solutions,US,Public,Alpha,Live Network Assurance,9,7,7,Stage 6 testing. Stable tollbooth catching wear-out degradation on live deployed networks.,,,
OPTX,Syntec Optics,US,Public,Moonshot,Polymer Optics & Micro-lens arrays,9,2,10,"Domestic MoD/Datacenter exposure. Low liquidity micro-cap. High risk, extreme upside.",,,
LITE,Lumentum,US,Public,Alpha,EML Lasers (800G/1.6T),9,5,4,Nvidia locked up capacity. Sold out of EML capacity through 2028. Critical optical bottleneck.,,,
AAOI,Applied Optoelectronics,US,Public,Alpha,Volume 1.6T Transceivers,9,4,6,Ramping aggressive hyperscaler buildouts (suspected Oracle). Building massive 210k sqft facility.,,,
NOK,Nokia,Finland,Public,Core,AI-RAN Distributed Compute,8,7,8,Pioneering AI-RAN via distributed cell tower GPU clusters integrated with Nvidia RTX.,,,
COHR,Coherent,US,Public,Alpha,EML Lasers & Transceivers,9,5,4,"Leading DSP/Laser maker,  capacity lockup by Nvidia.",,,
KEYS,Keysight Technologies,US,Public,Core,Testing / Oscilloscopes,8,8,4,Pick-and-shovel testing infrastructure for 800G/1.6T environments.,,,
CAMT,Camtek,Israel,Public,Alpha,Metrology / Packaging Inspection,8,7,5,Inspection tooling for advanced AI packaging and chiplet integration.,,,
`;